### ISSUE TITLE
Discord RPC Error/npm build error

### ISSUE THREAD

**Issue by JustAiden9** [HybrisMC/HybrProxy#3]
When I do npm, everything works until It gets to these lines below.
 Discord RPC   ERROR  Failed to login to Discord RPC Could not connect
 Discord RPC   ERROR  Cannot read properties of null (reading 'write')
Also when I run npm build it fails,

-  Bundling main process...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

**Comment by JustAiden9** [comment]
Full error
-------------------------------

PS C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy> npm run build

> hybrproxy@1.0.0-dev build
> npm run clean && node ./scripts/build.js


> hybrproxy@1.0.0-dev clean
> node ./scripts/clean.js

info: cleaning build folder... 🏗️
info: clean complete! 🗑️

info: compiling typescript 💽
info: obfuscating stats module 🔒
info: stats module was not present, skipping obfuscation ⏭️
info: building dashboard 🌐

> dashboard@1.0.0 build
> npm run setupCWD && vue-cli-service electron:build


> dashboard@1.0.0 setupCWD
> node setupCWD.js

Setup Dashboard CWD!
 INFO  Bundling render process:
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠼  Building for production...

 DONE  Compiled successfully in 2226ms                                                                       10:45:52 AM

  File                                         Size                               Gzipped

  dist\bundled\js\chunk-vendors.0cfaad4d.js    85.65 KiB                          31.09 KiB
  dist\bundled\js\app.135c5adf.js              23.21 KiB                          7.09 KiB
  dist\bundled\css\app.280ec109.css            13.61 KiB                          3.20 KiB

  Images and other types of assets omitted.
  Build at: 2023-06-06T15:45:52.524Z - Hash: 1d820e96e75e749a - Time: 2226ms

 DONE  Build complete. The dist\bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

-  Bundling main process...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\vue-cli-plugin-electron-builder\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\dashboard\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.7.2
node:child_process:902
    throw err;
    ^

Error: Command failed: cd dashboard && npm run build
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at run (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\scripts\build.js:4:3)
    at Object.<anonymous> (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\scripts\build.js:18:3)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19304,
  stdout: null,
  stderr: null
}

**Comment by JustAiden9** [comment]
I fixed the discord RPC, but I get this error still.

 INFO  Proxy started
(node:28420) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
 Dashboard   INFO  Dashboard WebSocket Online at port 7777
 Discord RPC   INFO  Authed for user JustAiden
C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\build\ErrorCatcher.js:31
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at join (node:path:429:7)
    at Timeout._onTimeout (C:\Users\aiden\OneDrive\Desktop\HyStats\HybrProxy\build\dashboard.js:39:58) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.7.2

**Comment by JustAiden9** [comment]
Might be because npm build did not work correctly

**Comment by TBHGodPro** [comment]
Use nodejs v16 to build and run, this is due to an electron issue

**Comment by JustAiden9** [comment]
Will it not work with node js 17

**Comment by TBHGodPro** [comment]
no

**Comment by JustAiden9** [comment]
I installed node js 16.16.0 and in the error it still says node js 17

Error: Command failed: cd dashboard && npm run build
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at run (C:\Users\aiden\OneDrive\Desktop\HybrProxy\scripts\build.js:4:3)
    at Object.<anonymous> (C:\Users\aiden\OneDrive\Desktop\HybrProxy\scripts\build.js:18:3)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 26252,
  stdout: null,
  stderr: null
}

Node.js v17.7.2

**Comment by qualk** [comment]
You need to set it to path, just use `nvm-windows` for Windows and `nvm` for MacOS and Linux @JustAiden9.

**Comment by raydreams** [comment]
Hello, @JustAiden9 

As stated previously, NodeJs 16 is required for this. I can understand that your PC is set to NodeJs 17.

As @qualk stated 1d ago, You need to set it to path for NodeJs. You can use ``nvm-windows`` Windows and ``nvm`` for MacOS and Linux.

Also, it’s recommended to use the NodeJs 16 Link found in the readme.md file (v.16.20.0) according to the developer(s).
